### ISSUE TITLE
It’s only converting <?php to @php. It’s not converting echo, if conditions and while and all conditions 

### ISSUE THREAD

**Issue by VenkatRamanaReddyMarri** [smarteist/PHP2Blade#8]
It’s only converting <?php to @php. It’s not converting echo, if conditions and while and all conditions

**Comment by smarteist** [comment]
> 

If your HTML code is written inside the php tags, it is not possible for now to convert it to blade syntax. Your code must be written all the conditions in html embeded form, please see [Alternative syntax for control structures](https://www.php.net/manual/en/control-structures.alternative-syntax.php). 
Otherwise it stays the same, please look at the readme examples.

**Comment by oknoote** [comment]
Ok I understand, was using a lot of HTML assignments to PHP variables in my templates.
